### ISSUE TITLE
No 403 error response and stdout option doesn't work with less

### ISSUE THREAD

**Issue by demianrey** [EdoardoVignati/ResponseThief#1]
First of all, thanks for this great tool, it can improve with what is described in the title ... by the way, I'm Damian, I spoke to you on telegram.
enjoy your vacations
regards

**Comment by EdoardoVignati** [comment]
Hi @demianrey and thank you for opening this issue.

I pushed some new fixes. 

I fixed the `less` option replacing it with `minimal` and now should work.

Can you provide me a 403 url that doesn't work in your experiment?
